environment:
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.11"
  - nodejs_version: "0.12"
  - nodejs_version: "4.0"
platform:
  - x86
  - x64
install:
  - npm install -g gulp
  - npm install -g bower
  - bower install
  - npm install
build_script:
  - gulp
test_script:
  - npm test
